server:
  port: 8761

spring:
  application:
    name: spring-registry
  cloud:
    config:
      import: optional:configserver

eureka:
  client:
    registry-with-eureka: false
    fetch-registry: false